### PR TITLE
Add customizable delay after the treshold is reached

### LINKED ISSUE #27: Re-Add delay
The readme on spigotmc.org mentions a config named delay in the default config.

This setting doesnt seem to exist anymore.
My proposal would be to either re-add the feature or update the readme.

Personally we don't like the instant-skip, so a feature to add a delay would be great, the default value can still be no delay it this is the desired effect on your side.

### PR DESCRIPTION
**Pull request by Joniator**
Fixes #27

### CODE REVIEW

**Comment by BytewaveMLP** [comment]
👍  I use plugins like BetterBeds (and how Harbor) on smaller servers, and the lack of delay is quite jarring.

The default delay Minecraft uses is 5 seconds, for others' reference, should they want to emulate vanilla.

**Comment by FireController1847** [comment]
@nkomarn Would love to see this added to the plugin!

**Comment by animeavi** [comment]
Been using the plugin with this patch for 2-3 weeks in my server and it hasn't cause any issues.

**Comment by nkomarn** [comment]
In the latest commit, I have implemented a smooth night transition, which would remove the need for this patch! Thank you for the feedback!

**Pull request closed without merging**
